# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'xm_weather.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1120, 810)
        MainWindow.setMinimumSize(QtCore.QSize(1120, 810))
        MainWindow.setMaximumSize(QtCore.QSize(1120, 810))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/Administrator/.designer/icon/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        MainWindow.setIconSize(QtCore.QSize(24, 24))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(1120, 810))
        self.centralwidget.setMaximumSize(QtCore.QSize(1120, 810))
        self.centralwidget.setObjectName("centralwidget")
        self.Left_widget = QtWidgets.QWidget(self.centralwidget)
        self.Left_widget.setGeometry(QtCore.QRect(0, 0, 245, 810))
        self.Left_widget.setMinimumSize(QtCore.QSize(245, 810))
        self.Left_widget.setMaximumSize(QtCore.QSize(245, 810))
        self.Left_widget.setStyleSheet("background-color: rgb(97, 101, 247);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;")
        self.Left_widget.setObjectName("Left_widget")
        self.Title_label = QtWidgets.QLabel(self.Left_widget)
        self.Title_label.setGeometry(QtCore.QRect(75, 23, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Title_label.setFont(font)
        self.Title_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.Title_label.setObjectName("Title_label")
        self.layoutWidget = QtWidgets.QWidget(self.Left_widget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 280, 247, 172))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Dashboard_Button = QtWidgets.QPushButton(self.layoutWidget)
        self.Dashboard_Button.setMinimumSize(QtCore.QSize(245, 30))
        self.Dashboard_Button.setMaximumSize(QtCore.QSize(245, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(13)
        self.Dashboard_Button.setFont(font)
        self.Dashboard_Button.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-image:url(../icon/dashboard.png);")
        self.Dashboard_Button.setText("")
        self.Dashboard_Button.setObjectName("Dashboard_Button")
        self.verticalLayout.addWidget(self.Dashboard_Button)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.Statistics_Button = QtWidgets.QPushButton(self.layoutWidget)
        self.Statistics_Button.setMinimumSize(QtCore.QSize(245, 30))
        self.Statistics_Button.setMaximumSize(QtCore.QSize(245, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(13)
        self.Statistics_Button.setFont(font)
        self.Statistics_Button.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-image:url(../icon/statistics.png);")
        self.Statistics_Button.setText("")
        self.Statistics_Button.setObjectName("Statistics_Button")
        self.verticalLayout.addWidget(self.Statistics_Button)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.Seting_Button = QtWidgets.QPushButton(self.layoutWidget)
        self.Seting_Button.setMinimumSize(QtCore.QSize(245, 30))
        self.Seting_Button.setMaximumSize(QtCore.QSize(245, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(13)
        self.Seting_Button.setFont(font)
        self.Seting_Button.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-image:url(../icon/setting.png);")
        self.Seting_Button.setText("")
        self.Seting_Button.setObjectName("Seting_Button")
        self.verticalLayout.addWidget(self.Seting_Button)
        self.Msg_Label = QtWidgets.QLabel(self.Left_widget)
        self.Msg_Label.setGeometry(QtCore.QRect(31, 453, 180, 330))
        self.Msg_Label.setMinimumSize(QtCore.QSize(180, 330))
        self.Msg_Label.setMaximumSize(QtCore.QSize(185, 330))
        self.Msg_Label.setStyleSheet("background-color: rgb(255, 255, 255);border-radius:10px;")
        self.Msg_Label.setText("")
        self.Msg_Label.setObjectName("Msg_Label")
        self.Msg_icon = QtWidgets.QLabel(self.Left_widget)
        self.Msg_icon.setGeometry(QtCore.QRect(53, 479, 60, 60))
        self.Msg_icon.setMinimumSize(QtCore.QSize(60, 60))
        self.Msg_icon.setMaximumSize(QtCore.QSize(60, 60))
        self.Msg_icon.setStyleSheet("border-radius:10px;\n"
"background-image:url(../icon/quality.png);\n"
"background-color:none;")
        self.Msg_icon.setText("")
        self.Msg_icon.setObjectName("Msg_icon")
        self.Msg_Days = QtWidgets.QLabel(self.Left_widget)
        self.Msg_Days.setGeometry(QtCore.QRect(120, 480, 50, 20))
        self.Msg_Days.setMinimumSize(QtCore.QSize(50, 20))
        self.Msg_Days.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(13)
        self.Msg_Days.setFont(font)
        self.Msg_Days.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Msg_Days.setObjectName("Msg_Days")
        self.Msg_Time = QtWidgets.QLabel(self.Left_widget)
        self.Msg_Time.setGeometry(QtCore.QRect(121, 511, 50, 15))
        self.Msg_Time.setMinimumSize(QtCore.QSize(50, 15))
        self.Msg_Time.setMaximumSize(QtCore.QSize(50, 15))
        font = QtGui.QFont()
        font.setFamily("等线 Light")
        font.setPointSize(10)
        self.Msg_Time.setFont(font)
        self.Msg_Time.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Msg_Time.setObjectName("Msg_Time")
        self.Msg_Date = QtWidgets.QLabel(self.Left_widget)
        self.Msg_Date.setGeometry(QtCore.QRect(121, 527, 80, 15))
        self.Msg_Date.setMinimumSize(QtCore.QSize(80, 15))
        self.Msg_Date.setMaximumSize(QtCore.QSize(80, 15))
        font = QtGui.QFont()
        font.setFamily("等线 Light")
        font.setPointSize(10)
        self.Msg_Date.setFont(font)
        self.Msg_Date.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Msg_Date.setObjectName("Msg_Date")
        self.Msg_Temper = QtWidgets.QLabel(self.Left_widget)
        self.Msg_Temper.setGeometry(QtCore.QRect(31, 560, 180, 60))
        self.Msg_Temper.setMinimumSize(QtCore.QSize(180, 60))
        self.Msg_Temper.setMaximumSize(QtCore.QSize(185, 60))
        font = QtGui.QFont()
        font.setFamily("等线 Light")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.Msg_Temper.setFont(font)
        self.Msg_Temper.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(255, 255, 255);")
        self.Msg_Temper.setAlignment(QtCore.Qt.AlignCenter)
        self.Msg_Temper.setObjectName("Msg_Temper")
        self.Msg_City = QtWidgets.QLabel(self.Left_widget)
        self.Msg_City.setGeometry(QtCore.QRect(31, 621, 180, 25))
        self.Msg_City.setMinimumSize(QtCore.QSize(180, 25))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(15)
        self.Msg_City.setFont(font)
        self.Msg_City.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Msg_City.setAlignment(QtCore.Qt.AlignCenter)
        self.Msg_City.setObjectName("Msg_City")
        self.Msg_Humidity = QtWidgets.QLabel(self.Left_widget)
        self.Msg_Humidity.setGeometry(QtCore.QRect(57, 669, 30, 15))
        self.Msg_Humidity.setMinimumSize(QtCore.QSize(30, 15))
        self.Msg_Humidity.setMaximumSize(QtCore.QSize(30, 15))
        font = QtGui.QFont()
        font.setFamily("等线")
        self.Msg_Humidity.setFont(font)
        self.Msg_Humidity.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Msg_Humidity.setObjectName("Msg_Humidity")
        self.Msg_Scale1 = QtWidgets.QLabel(self.Left_widget)
        self.Msg_Scale1.setGeometry(QtCore.QRect(167, 669, 30, 15))
        self.Msg_Scale1.setMinimumSize(QtCore.QSize(30, 15))
        self.Msg_Scale1.setMaximumSize(QtCore.QSize(30, 15))
        font = QtGui.QFont()
        font.setFamily("等线")
        self.Msg_Scale1.setFont(font)
        self.Msg_Scale1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Msg_Scale1.setObjectName("Msg_Scale1")
        self.Msg_Scale2 = QtWidgets.QLabel(self.Left_widget)
        self.Msg_Scale2.setGeometry(QtCore.QRect(167, 719, 30, 15))
        self.Msg_Scale2.setMinimumSize(QtCore.QSize(30, 15))
        self.Msg_Scale2.setMaximumSize(QtCore.QSize(30, 15))
        font = QtGui.QFont()
        font.setFamily("等线")
        self.Msg_Scale2.setFont(font)
        self.Msg_Scale2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Msg_Scale2.setObjectName("Msg_Scale2")
        self.Msg_Precipitation = QtWidgets.QLabel(self.Left_widget)
        self.Msg_Precipitation.setGeometry(QtCore.QRect(57, 719, 40, 15))
        self.Msg_Precipitation.setMinimumSize(QtCore.QSize(40, 15))
        self.Msg_Precipitation.setMaximumSize(QtCore.QSize(40, 15))
        font = QtGui.QFont()
        font.setFamily("等线")
        self.Msg_Precipitation.setFont(font)
        self.Msg_Precipitation.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Msg_Precipitation.setObjectName("Msg_Precipitation")
        self.Msg_Bar1 = QtWidgets.QProgressBar(self.Left_widget)
        self.Msg_Bar1.setGeometry(QtCore.QRect(56, 699, 131, 4))
        self.Msg_Bar1.setMinimumSize(QtCore.QSize(131, 4))
        self.Msg_Bar1.setMaximumSize(QtCore.QSize(4, 3))
        self.Msg_Bar1.setStyleSheet("QProgressBar {border: 2px ;   border-radius: 1.5px; background-color: rgb(216, 216, 216);}\n"
"::chunk {background-color: rgb(255, 173, 71);}\n"
"\n"
"")
        self.Msg_Bar1.setProperty("value", 60)
        self.Msg_Bar1.setAlignment(QtCore.Qt.AlignCenter)
        self.Msg_Bar1.setFormat("")
        self.Msg_Bar1.setObjectName("Msg_Bar1")
        self.Msg_Bar1_2 = QtWidgets.QProgressBar(self.Left_widget)
        self.Msg_Bar1_2.setGeometry(QtCore.QRect(55, 747, 131, 4))
        self.Msg_Bar1_2.setMinimumSize(QtCore.QSize(131, 4))
        self.Msg_Bar1_2.setMaximumSize(QtCore.QSize(4, 3))
        self.Msg_Bar1_2.setStyleSheet("QProgressBar::chunk {background-color: rgb(255, 173, 71);}\n"
"QProgressBar {border: 2px ;   border-radius: 1.5px; background-color: rgb(216, 216, 216);}\n"
"\n"
"")
        self.Msg_Bar1_2.setProperty("value", 60)
        self.Msg_Bar1_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Msg_Bar1_2.setFormat("")
        self.Msg_Bar1_2.setObjectName("Msg_Bar1_2")
        self.label_3 = QtWidgets.QLabel(self.Left_widget)
        self.label_3.setGeometry(QtCore.QRect(24, 20, 43, 41))
        self.label_3.setMinimumSize(QtCore.QSize(43, 41))
        self.label_3.setMaximumSize(QtCore.QSize(43, 41))
        self.label_3.setStyleSheet("background-image:url(../icon/logo.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.listWidget_2 = QtWidgets.QListWidget(self.Left_widget)
        self.listWidget_2.setGeometry(QtCore.QRect(0, 110, 245, 171))
        self.listWidget_2.setMinimumSize(QtCore.QSize(245, 0))
        self.listWidget_2.setMaximumSize(QtCore.QSize(245, 245))
        self.listWidget_2.setStyleSheet("QListWidget::Item:selected {\n"
"    border-left: 5px solid rgb(255,255,255);\n"
"    color:rgb(255,255,255);\n"
"}\n"
"QListWidget::Item:hover {\n"
"    border-left: 5px solid rgb(255,255,255);\n"
"}")
        self.listWidget_2.setLineWidth(1)
        self.listWidget_2.setIconSize(QtCore.QSize(60, 60))
        self.listWidget_2.setModelColumn(0)
        self.listWidget_2.setObjectName("listWidget_2")
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(16)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(16)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(16)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.listWidget_2.addItem(item)
        self.listWidget_2.raise_()
        self.Title_label.raise_()
        self.layoutWidget.raise_()
        self.Msg_Label.raise_()
        self.Msg_icon.raise_()
        self.Msg_Days.raise_()
        self.Msg_Time.raise_()
        self.Msg_Date.raise_()
        self.Msg_Temper.raise_()
        self.Msg_City.raise_()
        self.Msg_Humidity.raise_()
        self.Msg_Scale1.raise_()
        self.Msg_Scale2.raise_()
        self.Msg_Precipitation.raise_()
        self.Msg_Bar1.raise_()
        self.Msg_Bar1_2.raise_()
        self.label_3.raise_()
        self.Right_widget = QtWidgets.QWidget(self.centralwidget)
        self.Right_widget.setGeometry(QtCore.QRect(245, 0, 875, 810))
        self.Right_widget.setMinimumSize(QtCore.QSize(860, 810))
        self.Right_widget.setMaximumSize(QtCore.QSize(875, 810))
        self.Right_widget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;")
        self.Right_widget.setObjectName("Right_widget")
        self.City_label = QtWidgets.QLabel(self.Right_widget)
        self.City_label.setGeometry(QtCore.QRect(30, 77, 54, 30))
        self.City_label.setMinimumSize(QtCore.QSize(0, 30))
        self.City_label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.City_label.setFont(font)
        self.City_label.setObjectName("City_label")
        self.Quality_label = QtWidgets.QLabel(self.Right_widget)
        self.Quality_label.setGeometry(QtCore.QRect(30, 302, 161, 30))
        self.Quality_label.setMinimumSize(QtCore.QSize(0, 30))
        self.Quality_label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.Quality_label.setFont(font)
        self.Quality_label.setObjectName("Quality_label")
        self.View_label = QtWidgets.QLabel(self.Right_widget)
        self.View_label.setGeometry(QtCore.QRect(30, 489, 191, 30))
        self.View_label.setMinimumSize(QtCore.QSize(0, 30))
        self.View_label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.View_label.setFont(font)
        self.View_label.setObjectName("View_label")
        self.layoutWidget1 = QtWidgets.QWidget(self.Right_widget)
        self.layoutWidget1.setGeometry(QtCore.QRect(14, 12, 841, 42))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.Search_Layout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.Search_Layout.setContentsMargins(0, 0, 0, 0)
        self.Search_Layout.setSpacing(0)
        self.Search_Layout.setObjectName("Search_Layout")
        self.Search_Label = QtWidgets.QLabel(self.layoutWidget1)
        self.Search_Label.setMinimumSize(QtCore.QSize(40, 40))
        self.Search_Label.setMaximumSize(QtCore.QSize(40, 39))
        self.Search_Label.setStyleSheet("background-image:url(./icon/search.png);")
        self.Search_Label.setText("")
        self.Search_Label.setObjectName("Search_Label")
        self.Search_Layout.addWidget(self.Search_Label)
        spacerItem2 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.Search_Layout.addItem(spacerItem2)
        self.Search_lineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.Search_lineEdit.setMinimumSize(QtCore.QSize(250, 23))
        self.Search_lineEdit.setMaximumSize(QtCore.QSize(250, 23))
        self.Search_lineEdit.setStyleSheet("border-radius:10px;\n"
"border-color: rgb(223, 223, 223);\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"padding-left:7px\n"
"")
        self.Search_lineEdit.setText("")
        self.Search_lineEdit.setObjectName("Search_lineEdit")
        self.Search_Layout.addWidget(self.Search_lineEdit)
        spacerItem3 = QtWidgets.QSpacerItem(240, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.Search_Layout.addItem(spacerItem3)
        self.User_Button = QtWidgets.QPushButton(self.layoutWidget1)
        self.User_Button.setMinimumSize(QtCore.QSize(33, 33))
        self.User_Button.setMaximumSize(QtCore.QSize(33, 33))
        self.User_Button.setStyleSheet("border-radius:17px;\n"
"background-image:url(../icon/user.png);\n"
"\n"
"")
        self.User_Button.setText("")
        self.User_Button.setObjectName("User_Button")
        self.Search_Layout.addWidget(self.User_Button)
        self.Info_Box = QtWidgets.QComboBox(self.layoutWidget1)
        self.Info_Box.setMinimumSize(QtCore.QSize(110, 22))
        self.Info_Box.setMaximumSize(QtCore.QSize(110, 22))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.Info_Box.setFont(font)
        self.Info_Box.setStyleSheet("QComboBox{\n"
"border-color:#C8C8C8;\n"
"color: rgb(80, 80, 80);\n"
"padding-left: 10px;\n"
"}\n"
"::drop-down{\n"
"    border: none; \n"
"}\n"
"::down-arrow\n"
"{\n"
"    border-image:url(../icon/drop_down.png);\n"
"}\n"
"\n"
"")
        self.Info_Box.setObjectName("Info_Box")
        self.Info_Box.addItem("")
        self.Info_Box.addItem("")
        self.Info_Box.addItem("")
        self.Info_Box.addItem("")
        self.Search_Layout.addWidget(self.Info_Box)
        spacerItem4 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.Search_Layout.addItem(spacerItem4)
        self.Dividing_Search = QtWidgets.QLabel(self.layoutWidget1)
        self.Dividing_Search.setMinimumSize(QtCore.QSize(8, 20))
        self.Dividing_Search.setMaximumSize(QtCore.QSize(8, 20))
        font = QtGui.QFont()
        font.setFamily("隶书")
        font.setPointSize(15)
        self.Dividing_Search.setFont(font)
        self.Dividing_Search.setObjectName("Dividing_Search")
        self.Search_Layout.addWidget(self.Dividing_Search)
        spacerItem5 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.Search_Layout.addItem(spacerItem5)
        self.Min_Button = QtWidgets.QPushButton(self.layoutWidget1)
        self.Min_Button.setMinimumSize(QtCore.QSize(25, 25))
        self.Min_Button.setMaximumSize(QtCore.QSize(25, 25))
        self.Min_Button.setStyleSheet("QPushButton{background:#6DDF6D;border-radius:5px;}\n"
"::hover{background:green;}")
        self.Min_Button.setObjectName("Min_Button")
        self.Search_Layout.addWidget(self.Min_Button)
        spacerItem6 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.Search_Layout.addItem(spacerItem6)
        self.Close_Button = QtWidgets.QPushButton(self.layoutWidget1)
        self.Close_Button.setMinimumSize(QtCore.QSize(25, 25))
        self.Close_Button.setMaximumSize(QtCore.QSize(25, 25))
        self.Close_Button.setStyleSheet("QPushButton{background:#F76677;border-radius:5px;}QPushButton:hover{background:red;}")
        self.Close_Button.setObjectName("Close_Button")
        self.Search_Layout.addWidget(self.Close_Button)
        self.City_Scroll = QtWidgets.QScrollArea(self.Right_widget)
        self.City_Scroll.setGeometry(QtCore.QRect(40, 118, 791, 170))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.City_Scroll.sizePolicy().hasHeightForWidth())
        self.City_Scroll.setSizePolicy(sizePolicy)
        self.City_Scroll.setMinimumSize(QtCore.QSize(791, 170))
        self.City_Scroll.setMaximumSize(QtCore.QSize(791, 170))
        self.City_Scroll.setFrameShadow(QtWidgets.QFrame.Plain)
        self.City_Scroll.setLineWidth(1)
        self.City_Scroll.setMidLineWidth(0)
        self.City_Scroll.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.City_Scroll.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.City_Scroll.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.City_Scroll.setWidgetResizable(True)
        self.City_Scroll.setAlignment(QtCore.Qt.AlignCenter)
        self.City_Scroll.setObjectName("City_Scroll")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 791, 170))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.City_Button = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.City_Button.setGeometry(QtCore.QRect(2, 18, 145, 110))
        self.City_Button.setMinimumSize(QtCore.QSize(145, 110))
        self.City_Button.setMaximumSize(QtCore.QSize(145, 110))
        self.City_Button.setStyleSheet("background-image:url(../city_pictures/test.png);\n"
"border-radius:10px;")
        self.City_Button.setText("")
        self.City_Button.setObjectName("City_Button")
        self.City_Name = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.City_Name.setGeometry(QtCore.QRect(2, 134, 145, 20))
        self.City_Name.setMinimumSize(QtCore.QSize(145, 20))
        self.City_Name.setMaximumSize(QtCore.QSize(145, 20))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.City_Name.setFont(font)
        self.City_Name.setObjectName("City_Name")
        self.City_Scroll.setWidget(self.scrollAreaWidgetContents)
        self.Air_Scroll = QtWidgets.QScrollArea(self.Right_widget)
        self.Air_Scroll.setGeometry(QtCore.QRect(40, 346, 791, 121))
        self.Air_Scroll.setMinimumSize(QtCore.QSize(791, 121))
        self.Air_Scroll.setMaximumSize(QtCore.QSize(791, 121))
        self.Air_Scroll.setWidgetResizable(True)
        self.Air_Scroll.setObjectName("Air_Scroll")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 791, 121))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.Icon_Button = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.Icon_Button.setGeometry(QtCore.QRect(22, 10, 50, 50))
        self.Icon_Button.setMinimumSize(QtCore.QSize(50, 50))
        self.Icon_Button.setMaximumSize(QtCore.QSize(50, 50))
        self.Icon_Button.setStyleSheet("border-radius:0px;\n"
"background-color:none;\n"
"background-image:url(../icon/airQuality/pm10.png);")
        self.Icon_Button.setText("")
        self.Icon_Button.setObjectName("Icon_Button")
        self.Temperature_Back = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.Temperature_Back.setGeometry(QtCore.QRect(2, 5, 90, 110))
        self.Temperature_Back.setMinimumSize(QtCore.QSize(90, 110))
        self.Temperature_Back.setMaximumSize(QtCore.QSize(90, 110))
        self.Temperature_Back.setStyleSheet("border-radius:14px;\n"
"background-color: rgb(247, 247, 247);\n"
"border-color: rgb(223, 223, 223);\n"
"border-width: 1px;\n"
"border-style: solid;")
        self.Temperature_Back.setText("")
        self.Temperature_Back.setObjectName("Temperature_Back")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label.setGeometry(QtCore.QRect(7, 64, 80, 20))
        self.label.setMinimumSize(QtCore.QSize(80, 20))
        self.label.setMaximumSize(QtCore.QSize(80, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setStyleSheet("border-radius:0px;\n"
"background-color:none;")
        self.label.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.China))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_2.setGeometry(QtCore.QRect(7, 88, 80, 20))
        self.label_2.setMinimumSize(QtCore.QSize(80, 20))
        self.label_2.setMaximumSize(QtCore.QSize(80, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border-radius:0px;\n"
"background-color:none;")
        self.label_2.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.China))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.Temperature_Back_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.Temperature_Back_2.setGeometry(QtCore.QRect(140, 8, 90, 110))
        self.Temperature_Back_2.setMinimumSize(QtCore.QSize(90, 110))
        self.Temperature_Back_2.setMaximumSize(QtCore.QSize(90, 110))
        self.Temperature_Back_2.setStyleSheet("border-radius:14px;\n"
"background-color: rgb(247, 247, 247);\n"
"border-color: rgb(223, 223, 223);\n"
"border-width: 1px;\n"
"border-style: solid;")
        self.Temperature_Back_2.setText("")
        self.Temperature_Back_2.setObjectName("Temperature_Back_2")
        self.Temperature_Back_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.Temperature_Back_3.setGeometry(QtCore.QRect(262, 8, 90, 110))
        self.Temperature_Back_3.setMinimumSize(QtCore.QSize(90, 110))
        self.Temperature_Back_3.setMaximumSize(QtCore.QSize(90, 110))
        self.Temperature_Back_3.setStyleSheet("border-radius:14px;\n"
"background-color: rgb(247, 247, 247);\n"
"border-color: rgb(223, 223, 223);\n"
"border-width: 1px;\n"
"border-style: solid;")
        self.Temperature_Back_3.setText("")
        self.Temperature_Back_3.setObjectName("Temperature_Back_3")
        self.Temperature_Back_4 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.Temperature_Back_4.setGeometry(QtCore.QRect(380, 10, 90, 110))
        self.Temperature_Back_4.setMinimumSize(QtCore.QSize(90, 110))
        self.Temperature_Back_4.setMaximumSize(QtCore.QSize(90, 110))
        self.Temperature_Back_4.setStyleSheet("border-radius:14px;\n"
"background-color: rgb(247, 247, 247);\n"
"border-color: rgb(223, 223, 223);\n"
"border-width: 1px;\n"
"border-style: solid;")
        self.Temperature_Back_4.setText("")
        self.Temperature_Back_4.setObjectName("Temperature_Back_4")
        self.Temperature_Back_5 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.Temperature_Back_5.setGeometry(QtCore.QRect(510, 10, 90, 110))
        self.Temperature_Back_5.setMinimumSize(QtCore.QSize(90, 110))
        self.Temperature_Back_5.setMaximumSize(QtCore.QSize(90, 110))
        self.Temperature_Back_5.setStyleSheet("border-radius:14px;\n"
"background-color: rgb(247, 247, 247);\n"
"border-color: rgb(223, 223, 223);\n"
"border-width: 1px;\n"
"border-style: solid;")
        self.Temperature_Back_5.setText("")
        self.Temperature_Back_5.setObjectName("Temperature_Back_5")
        self.Temperature_Back_6 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.Temperature_Back_6.setGeometry(QtCore.QRect(630, 10, 90, 110))
        self.Temperature_Back_6.setMinimumSize(QtCore.QSize(90, 110))
        self.Temperature_Back_6.setMaximumSize(QtCore.QSize(90, 110))
        self.Temperature_Back_6.setStyleSheet("border-radius:14px;\n"
"background-color: rgb(247, 247, 247);\n"
"border-color: rgb(223, 223, 223);\n"
"border-width: 1px;\n"
"border-style: solid;")
        self.Temperature_Back_6.setText("")
        self.Temperature_Back_6.setObjectName("Temperature_Back_6")
        self.Temperature_Back.raise_()
        self.Icon_Button.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.Temperature_Back_2.raise_()
        self.Temperature_Back_3.raise_()
        self.Temperature_Back_4.raise_()
        self.Temperature_Back_5.raise_()
        self.Temperature_Back_6.raise_()
        self.Air_Scroll.setWidget(self.scrollAreaWidgetContents_2)
        self.Dividing_Quality1 = QtWidgets.QLabel(self.Right_widget)
        self.Dividing_Quality1.setGeometry(QtCore.QRect(176, 539, 10, 20))
        self.Dividing_Quality1.setMinimumSize(QtCore.QSize(10, 20))
        self.Dividing_Quality1.setMaximumSize(QtCore.QSize(10, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Dividing_Quality1.setFont(font)
        self.Dividing_Quality1.setStyleSheet("background-color:none;")
        self.Dividing_Quality1.setObjectName("Dividing_Quality1")
        self.Quality_Button = QtWidgets.QPushButton(self.Right_widget)
        self.Quality_Button.setGeometry(QtCore.QRect(192, 537, 55, 25))
        self.Quality_Button.setMinimumSize(QtCore.QSize(55, 25))
        self.Quality_Button.setMaximumSize(QtCore.QSize(55, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.Quality_Button.setFont(font)
        self.Quality_Button.setStyleSheet("background-color:none;")
        self.Quality_Button.setObjectName("Quality_Button")
        self.Type_Box = QtWidgets.QComboBox(self.Right_widget)
        self.Type_Box.setGeometry(QtCore.QRect(662, 538, 70, 22))
        self.Type_Box.setMinimumSize(QtCore.QSize(70, 22))
        self.Type_Box.setMaximumSize(QtCore.QSize(70, 22))
        self.Type_Box.setStyleSheet("QComboBox{\n"
"border-color:#C8C8C8;\n"
"color: rgb(80, 80, 80);\n"
"border-style:solid;\n"
"border-width: 0.5 0.5 0.5 0.5;\n"
"border-radius: 4px;\n"
"padding-left: 5px;\n"
"}\n"
"::drop-down{\n"
"    border: none; \n"
"}\n"
"::down-arrow\n"
"{\n"
"    border-image:url(../icon/drop_down.png);\n"
"}\n"
"\n"
"")
        self.Type_Box.setObjectName("Type_Box")
        self.Type_Box.addItem("")
        self.Type_Box.addItem("")
        self.Type_Box.addItem("")
        self.Type_Box.addItem("")
        self.Type_Box.addItem("")
        self.Type_Box.addItem("")
        self.Type_Box.addItem("")
        self.View_Box = QtWidgets.QComboBox(self.Right_widget)
        self.View_Box.setGeometry(QtCore.QRect(738, 538, 70, 22))
        self.View_Box.setMinimumSize(QtCore.QSize(70, 22))
        self.View_Box.setMaximumSize(QtCore.QSize(70, 22))
        self.View_Box.setStyleSheet("QComboBox{\n"
"border-color:#C8C8C8;\n"
"color: rgb(80, 80, 80);\n"
"border-style:solid;\n"
"border-width: 0.5 0.5 0.5 0.5;\n"
"border-radius: 4px;\n"
"padding-left: 7px;\n"
"}\n"
"::drop-down{\n"
"    border: none; \n"
"}\n"
"::down-arrow\n"
"{\n"
"    border-image:url(../icon/drop_down.png);\n"
"}\n"
"\n"
"")
        self.View_Box.setObjectName("View_Box")
        self.View_Box.addItem("")
        self.View_Box.addItem("")
        self.View_Box.addItem("")
        self.Times_Button = QtWidgets.QPushButton(self.Right_widget)
        self.Times_Button.setGeometry(QtCore.QRect(58, 537, 50, 25))
        self.Times_Button.setMinimumSize(QtCore.QSize(50, 25))
        self.Times_Button.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.Times_Button.setFont(font)
        self.Times_Button.setStyleSheet("background-color:none;")
        self.Times_Button.setObjectName("Times_Button")
        self.Dividing_Quality = QtWidgets.QLabel(self.Right_widget)
        self.Dividing_Quality.setGeometry(QtCore.QRect(114, 539, 10, 20))
        self.Dividing_Quality.setMinimumSize(QtCore.QSize(10, 20))
        self.Dividing_Quality.setMaximumSize(QtCore.QSize(10, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Dividing_Quality.setFont(font)
        self.Dividing_Quality.setStyleSheet("background-color:none;")
        self.Dividing_Quality.setObjectName("Dividing_Quality")
        self.Day_Button = QtWidgets.QPushButton(self.Right_widget)
        self.Day_Button.setGeometry(QtCore.QRect(130, 537, 40, 25))
        self.Day_Button.setMinimumSize(QtCore.QSize(40, 25))
        self.Day_Button.setMaximumSize(QtCore.QSize(40, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.Day_Button.setFont(font)
        self.Day_Button.setStyleSheet("background-color:none;")
        self.Day_Button.setObjectName("Day_Button")
        self.Quality_View = QtWidgets.QLabel(self.Right_widget)
        self.Quality_View.setGeometry(QtCore.QRect(40, 555, 791, 230))
        self.Quality_View.setMinimumSize(QtCore.QSize(791, 230))
        self.Quality_View.setMaximumSize(QtCore.QSize(791, 230))
        self.Quality_View.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(247, 247, 247);\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-color:rgb(200,200,200);\n"
"border-top:none;\n"
"border-top-left-radius:0px;\n"
"border-top-right-radius:0px;")
        self.Quality_View.setText("")
        self.Quality_View.setObjectName("Quality_View")
        self.Quality_View_2 = QtWidgets.QLabel(self.Right_widget)
        self.Quality_View_2.setGeometry(QtCore.QRect(40, 530, 791, 27))
        self.Quality_View_2.setMinimumSize(QtCore.QSize(791, 27))
        self.Quality_View_2.setMaximumSize(QtCore.QSize(791, 27))
        self.Quality_View_2.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(247, 247, 247);\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-color:rgb(200,200,200);\n"
"border-bottom:none;\n"
"border-bottom-left-radius:0px;\n"
"border-bottom-right-radius:0px;")
        self.Quality_View_2.setText("")
        self.Quality_View_2.setObjectName("Quality_View_2")
        self.Quality_View_2.raise_()
        self.Quality_View.raise_()
        self.Dividing_Quality1.raise_()
        self.Quality_Button.raise_()
        self.Type_Box.raise_()
        self.Times_Button.raise_()
        self.Dividing_Quality.raise_()
        self.Day_Button.raise_()
        self.City_label.raise_()
        self.Quality_label.raise_()
        self.View_label.raise_()
        self.layoutWidget.raise_()
        self.City_Scroll.raise_()
        self.Air_Scroll.raise_()
        self.View_Box.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.Close_Button.clicked.connect(MainWindow.close)
        self.Min_Button.clicked.connect(MainWindow.showMinimized)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.Search_lineEdit, self.User_Button)
        MainWindow.setTabOrder(self.User_Button, self.Statistics_Button)
        MainWindow.setTabOrder(self.Statistics_Button, self.Seting_Button)
        MainWindow.setTabOrder(self.Seting_Button, self.Icon_Button)
        MainWindow.setTabOrder(self.Icon_Button, self.Close_Button)
        MainWindow.setTabOrder(self.Close_Button, self.Min_Button)
        MainWindow.setTabOrder(self.Min_Button, self.Quality_Button)
        MainWindow.setTabOrder(self.Quality_Button, self.View_Box)
        MainWindow.setTabOrder(self.View_Box, self.Type_Box)
        MainWindow.setTabOrder(self.Type_Box, self.Times_Button)
        MainWindow.setTabOrder(self.Times_Button, self.Day_Button)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "XM-Weathrer"))
        self.Title_label.setText(_translate("MainWindow", "XM-WEATHER"))
        self.Msg_Days.setText(_translate("MainWindow", "今天"))
        self.Msg_Time.setText(_translate("MainWindow", "20:20"))
        self.Msg_Date.setText(_translate("MainWindow", "2020/1/28"))
        self.Msg_Temper.setText(_translate("MainWindow", "+26℃"))
        self.Msg_City.setText(_translate("MainWindow", "德阳"))
        self.Msg_Humidity.setText(_translate("MainWindow", "湿度："))
        self.Msg_Scale1.setText(_translate("MainWindow", "60%"))
        self.Msg_Scale2.setText(_translate("MainWindow", "60%"))
        self.Msg_Precipitation.setText(_translate("MainWindow", "降水量："))
        __sortingEnabled = self.listWidget_2.isSortingEnabled()
        self.listWidget_2.setSortingEnabled(False)
        item = self.listWidget_2.item(0)
        item.setText(_translate("MainWindow", "  Dashboard"))
        item = self.listWidget_2.item(1)
        item.setText(_translate("MainWindow", "Statistics"))
        item = self.listWidget_2.item(2)
        item.setText(_translate("MainWindow", "Setting   "))
        self.listWidget_2.setSortingEnabled(__sortingEnabled)
        self.City_label.setText(_translate("MainWindow", "城市"))
        self.Quality_label.setText(_translate("MainWindow", "城市空气质量预报"))
        self.View_label.setText(_translate("MainWindow", "城市空气质量图"))
        self.Info_Box.setItemText(0, _translate("MainWindow", "User_Name"))
        self.Info_Box.setItemText(1, _translate("MainWindow", "个人信息"))
        self.Info_Box.setItemText(2, _translate("MainWindow", "切换帐号"))
        self.Info_Box.setItemText(3, _translate("MainWindow", "退出"))
        self.Dividing_Search.setText(_translate("MainWindow", "|"))
        self.Min_Button.setText(_translate("MainWindow", "—"))
        self.Close_Button.setText(_translate("MainWindow", "X"))
        self.City_Name.setText(_translate("MainWindow", "成都"))
        self.label.setText(_translate("MainWindow", "100~100"))
        self.label_2.setText(_translate("MainWindow", "11-22"))
        self.Dividing_Quality1.setText(_translate("MainWindow", "|"))
        self.Quality_Button.setText(_translate("MainWindow", "Quality"))
        self.Type_Box.setItemText(0, _translate("MainWindow", "AQI"))
        self.Type_Box.setItemText(1, _translate("MainWindow", "SO2"))
        self.Type_Box.setItemText(2, _translate("MainWindow", "NO2"))
        self.Type_Box.setItemText(3, _translate("MainWindow", "CO"))
        self.Type_Box.setItemText(4, _translate("MainWindow", "O3"))
        self.Type_Box.setItemText(5, _translate("MainWindow", "PM2.5"))
        self.Type_Box.setItemText(6, _translate("MainWindow", "PM10"))
        self.View_Box.setItemText(0, _translate("MainWindow", "列 表"))
        self.View_Box.setItemText(1, _translate("MainWindow", "曲 线"))
        self.View_Box.setItemText(2, _translate("MainWindow", "圆 饼"))
        self.Times_Button.setText(_translate("MainWindow", "Times"))
        self.Dividing_Quality.setText(_translate("MainWindow", "|"))
        self.Day_Button.setText(_translate("MainWindow", "Day"))
